# Plot top 5 miRNAs and cilnical variates
# Require to load 'spall-dist-ptab.rdata' first.

pdf('f5-milan.pdf')
par(mfrow=c(3,2))
plot(spall[,'hsa-miR-122_st'],col=c('green','red')[as.numeric(as.factor(spall$milan))],pch=c(16,17)[as.numeric(as.factor(spall$recur))],main='hsa-miR-122 & Milan (176 samples)',xlab='Index',ylab='hsa-miR-122')
title(main='A', adj=0)
plot(spall[,'hsa-miR-126_st'],col=c('green','red')[as.numeric(as.factor(spall$milan))],pch=c(16,17)[as.numeric(as.factor(spall$recur))],main='hsa-miR-126 & Milan (176 samples)',xlab='Index',ylab='hsa-miR-126')
title(main='B', adj=0)
plot(spall[,'hsa-miR-22_st'],col=c('green','red')[as.numeric(as.factor(spall$milan))],pch=c(16,17)[as.numeric(as.factor(spall$recur))],main='hsa-miR-22 & Milan (176 samples)',xlab='Index',ylab='hsa-miR-22')
title(main='C', adj=0)
plot(spall[,'hsa-miR-30a_st'],col=c('green','red')[as.numeric(as.factor(spall$milan))],pch=c(16,17)[as.numeric(as.factor(spall$recur))],main='hsa-miR-30a & Milan (176 samples)',xlab='Index',ylab='hsa-miR-30a')
title(main='D', adj=0)
plot(spall[,'hsa-miR-15a_st'],col=c('green','red')[as.numeric(as.factor(spall$milan))],pch=c(16,17)[as.numeric(as.factor(spall$recur))],main='hsa-miR-15a & Milan (176 samples)',xlab='Index',ylab='hsa-miR-15a')
title(main='F', adj=0)
plot.new()
legend('top', col=c('green','red'),pch=16,c('Outside','Within'),title='Milan')
legend('bottom',pch=c(1,2),c('No Recurrence','Recurrence'))
dev.off()

pdf('f5-vasc.pdf')
par(mfrow=c(3,2))
plot(spall[,'hsa-miR-122_st'],col=c('green','red')[as.numeric(as.factor(spall$vasc))],pch=c(16,17)[as.numeric(as.factor(spall$recur))],main='hsa-miR-122 & Vascularization (176 samples)',xlab='Index',ylab='hsa-miR-122')
title(main='A', adj=0)
plot(spall[,'hsa-miR-126_st'],col=c('green','red')[as.numeric(as.factor(spall$vasc))],pch=c(16,17)[as.numeric(as.factor(spall$recur))],main='hsa-miR-126 & Vascularization(176 samples)',xlab='Index',ylab='hsa-miR-126')
title(main='B', adj=0)
plot(spall[,'hsa-miR-22_st'],col=c('green','red')[as.numeric(as.factor(spall$vasc))],pch=c(16,17)[as.numeric(as.factor(spall$recur))],main='hsa-miR-22 & Vascularization (176 samples)',xlab='Index',ylab='hsa-miR-22')
title(main='C', adj=0)
plot(spall[,'hsa-miR-30a_st'],col=c('green','red')[as.numeric(as.factor(spall$vasc))],pch=c(16,17)[as.numeric(as.factor(spall$recur))],main='hsa-miR-30a & Vascularization(176 samples)',xlab='Index',ylab='hsa-miR-30a')
title(main='D', adj=0)
plot(spall[,'hsa-miR-15a_st'],col=c('green','red')[as.numeric(as.factor(spall$vasc))],pch=c(16,17)[as.numeric(as.factor(spall$recur))],main='hsa-miR-15a & Vascularization (176 samples)',xlab='Index',ylab='hsa-miR-15a')
title(main='F', adj=0)
plot.new()
legend('top', col=c('green','red'),pch=16,c('N','Y'),title='Vascularization')
legend('bottom',pch=c(1,2),c('No Recurrence','Recurrence'))

dev.off();


pdf('f5-tumorStage.pdf')
par(mfrow=c(3,2))
plot(spall[,'hsa-miR-122_st'],col=c('green','red','blue','black')[as.numeric(spall$Tumor.Stage)],pch=c(16,17)[as.numeric(as.factor(spall$recur))],main='hsa-miR-122 & Tumor Stage (176 samples)',xlab='Index',ylab='hsa-miR-122')
title(main='A', adj=0)
plot(spall[,'hsa-miR-126_st'],col=c('green','red','blue','black')[as.numeric(spall$Tumor.Stage)],pch=c(16,17)[as.numeric(as.factor(spall$recur))],main='hsa-miR-126 & Tumor Stage(176 samples)',xlab='Index',ylab='hsa-miR-126')
title(main='B', adj=0)
plot(spall[,'hsa-miR-22_st'],col=c('green','red','blue','black')[as.numeric(spall$Tumor.Stage)],pch=c(16,17)[as.numeric(as.factor(spall$recur))],main='hsa-miR-22 & Tumor Stage (176 samples)',xlab='Index',ylab='hsa-miR-22')
title(main='C', adj=0)
plot(spall[,'hsa-miR-30a_st'],col=c('green','red','blue','black')[as.numeric(spall$Tumor.Stage)],pch=c(16,17)[as.numeric(as.factor(spall$recur))],main='hsa-miR-30a & Tumor Stage (176 samples)',xlab='Index',ylab='hsa-miR-30a')
title(main='D', adj=0)
plot(spall[,'hsa-miR-15a_st'],col=c('green','red','blue','black')[as.numeric(spall$Tumor.Stage)],pch=c(16,17)[as.numeric(as.factor(spall$recur))],main='hsa-miR-15a & Tumor Stage (176 samples)',xlab='Index',ylab='hsa-miR-15a')
title(main='F', adj=0)
plot.new()
legend('top', col=c('green','red','blue','black'),pch=16,c('I','II','IIIA','IIIB'),title='Tumor Stage')
legend('bottom',pch=c(1,2),c('No Recurrence','Recurrence'))

dev.off();

pdf('f5-HCV.pdf')
par(mfrow=c(3,2))
plot(spall[,'hsa-miR-122_st'],col=c('green','red')[as.numeric(as.factor(spall$HCV))],pch=c(16,17)[as.numeric(as.factor(spall$recur))],main='hsa-miR-122 & HCV (176 samples)',xlab='Index',ylab='hsa-miR-122')
title(main='A', adj=0)
plot(spall[,'hsa-miR-126_st'],col=c('green','red')[as.numeric(as.factor(spall$HCV))],pch=c(16,17)[as.numeric(as.factor(spall$recur))],main='hsa-miR-126 & HCV (176 samples)',xlab='Index',ylab='hsa-miR-126')
title(main='B', adj=0)
plot(spall[,'hsa-miR-22_st'],col=c('green','red')[as.numeric(as.factor(spall$HCV))],pch=c(16,17)[as.numeric(as.factor(spall$recur))],main='hsa-miR-22 & HCV (176 samples)',xlab='Index',ylab='hsa-miR-22')
title(main='C', adj=0)
plot(spall[,'hsa-miR-30a_st'],col=c('green','red')[as.numeric(as.factor(spall$HCV))],pch=c(16,17)[as.numeric(as.factor(spall$recur))],main='hsa-miR-30a & HCV (176 samples)',xlab='Index',ylab='hsa-miR-30a')
title(main='D', adj=0)
plot(spall[,'hsa-miR-15a_st'],col=c('green','red')[as.numeric(as.factor(spall$HCV))],pch=c(16,17)[as.numeric(as.factor(spall$recur))],main='hsa-miR-15a & HCV (176 samples)',xlab='Index',ylab='hsa-miR-15a')
title(main='F', adj=0)
plot.new()
legend('top', col=c('green','red'),pch=16,c('N','Y'),title='HCV')
legend('bottom',pch=c(1,2),c('No Recurrence','Recurrence'))

dev.off();

pdf('f5-recur.pdf')
par(mfrow=c(3,2))
plot(spall[,'hsa-miR-122_st'],col=c('green','red')[as.numeric(as.factor(spall$recur))],pch=c(16,17)[as.numeric(as.factor(spall$recur))],main='hsa-miR-122 & Recurrence (176 samples)',xlab='Index',ylab='hsa-miR-122')
title(main='A', adj=0)
plot(spall[,'hsa-miR-126_st'],col=c('green','red')[as.numeric(as.factor(spall$recur))],pch=c(16,17)[as.numeric(as.factor(spall$recur))],main='hsa-miR-126 & Recurrence (176 samples)',xlab='Index',ylab='hsa-miR-126')
title(main='B', adj=0)
plot(spall[,'hsa-miR-22_st'],col=c('green','red')[as.numeric(as.factor(spall$recur))],pch=c(16,17)[as.numeric(as.factor(spall$recur))],main='hsa-miR-22 &  Recurrence  (176 samples)',xlab='Index',ylab='hsa-miR-22')
title(main='C', adj=0)
plot(spall[,'hsa-miR-30a_st'],col=c('green','red')[as.numeric(as.factor(spall$recur))],pch=c(16,17)[as.numeric(as.factor(spall$recur))],main='hsa-miR-30a & Recurrence (176 samples)',xlab='Index',ylab='hsa-miR-30a')
title(main='D', adj=0)
plot(spall[,'hsa-miR-15a_st'],col=c('green','red')[as.numeric(as.factor(spall$recur))],pch=c(16,17)[as.numeric(as.factor(spall$recur))],main='hsa-miR-15a & Recurrence (176 samples)',xlab='Index',ylab='hsa-miR-15a')
title(main='F', adj=0)
plot.new()
legend('top', col=c('green','red'),pch=c(16,17),c('No Recurrence','Recurrence'),title='HCC Recurrence')
dev.off()

